<div><label for="nama_peminjam" class="block text-sm font-medium text-gray-700">Nama Peminjam</label><input type="text" name="nama_peminjam" value="{{ old('nama_peminjam', $peminjaman->nama_peminjam ?? null) }}" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
<div><label for="tanggal_peminjaman" class="block text-sm font-medium text-gray-700">Tanggal Peminjaman</label><input type="date" name="tanggal_peminjaman" value="{{ old('tanggal_peminjaman', isset($peminjaman) ? $peminjaman->tanggal_peminjaman->format('Y-m-d') : date('Y-m-d')) }}" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
<div><label for="kode_barang" class="block text-sm font-medium text-gray-700">Barang yang Dipinjam</label><select name="kode_barang" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">-- Pilih Barang --</option>@foreach($barangs as $barang)<option value="{{ $barang->kode_barang }}" {{ old('kode_barang', $peminjaman->kode_barang ?? null) == $barang->kode_barang ? 'selected' : '' }}>{{ $barang->nama_barang }}</option>@endforeach</select></div>
<div class="grid grid-cols-2 gap-6">
    <div><label for="jumlah" class="block text-sm font-medium text-gray-700">Jumlah</label><input type="number" name="jumlah" value="{{ old('jumlah', $peminjaman->jumlah ?? null) }}" min="1" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
    <div><label for="id_satuan_pjm" class="block text-sm font-medium text-gray-700">Satuan</label><select name="id_satuan_pjm" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="">-- Pilih Satuan --</option>@foreach($satuans as $satuan)<option value="{{ $satuan->id }}" {{ old('id_satuan_pjm', $peminjaman->id_satuan_pjm ?? null) == $satuan->id ? 'selected' : '' }}>{{ $satuan->nama_satuan }}</option>@endforeach</select></div>
</div>
<div><label for="lama_peminjaman" class="block text-sm font-medium text-gray-700">Lama Peminjaman</label><input type="text" name="lama_peminjaman" value="{{ old('lama_peminjaman', $peminjaman->lama_peminjaman ?? null) }}" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm" placeholder="Contoh: 3 Hari, 1 Minggu"></div>
<div><label for="kondisi" class="block text-sm font-medium text-gray-700">Kondisi Barang Saat Dipinjam</label><select name="kondisi" required class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"><option value="Baik" {{ old('kondisi', $peminjaman->kondisi ?? 'Baik') == 'Baik' ? 'selected' : '' }}>Baik</option><option value="Rusak" {{ old('kondisi', $peminjaman->kondisi ?? null) == 'Rusak' ? 'selected' : '' }}>Rusak</option></select></div>
<div class="flex justify-end space-x-4 pt-4 border-t mt-6">
    <a href="{{ route('peminjaman.index') }}" class="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300 font-medium">Batal</a>
    <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 font-medium">{{ isset($peminjaman) ? 'Update' : 'Simpan' }}</button>
</div>